True# Generated by Django 5.0.4 on 2024-06-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('nit', models.DecimalField(db_column='Nit', decimal_places=10, max_digits=2, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('direccion', models.TextField()),
                ('telefono', models.DecimalField(decimal_places=10, max_digits=2)),
                ('email', models.TextField()),
            ],
            options={
                'db_table': 'Clientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('cod_inventario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('tipo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id_orden', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Orden_produccion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.TextField()),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transformulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('materia1', models.IntegerField(blank=True, null=True)),
                ('cant_materia1', models.FloatField(blank=True, null=True)),
                ('materia2', models.IntegerField(blank=True, null=True)),
                ('cant_materia2', models.FloatField(blank=True, null=True)),
                ('materia3', models.IntegerField(blank=True, null=True)),
                ('cant_materia3', models.FloatField(blank=True, null=True)),
                ('materia4', models.IntegerField(blank=True, null=True)),
                ('cant_materia4', models.FloatField(blank=True, null=True)),
                ('materia5', models.IntegerField(blank=True, null=True)),
                ('cant_materia5', models.FloatField(blank=True, null=True)),
                ('materia6', models.IntegerField(blank=True, null=True)),
                ('cant_materia6', models.FloatField(blank=True, null=True)),
                ('materia7', models.IntegerField(blank=True, null=True)),
                ('cant_materia7', models.FloatField(blank=True, null=True)),
                ('materia8', models.IntegerField(blank=True, null=True)),
                ('cant_materia8', models.FloatField(blank=True, null=True)),
                ('porcentajeiva', models.FloatField()),
                ('pocentajeutilidad', models.FloatField()),
                ('costosindirectos', models.FloatField()),
            ],
            options={
                'db_table': 'transformulas',
                'managed': True,
            },
        ),
    ]
