# Generated by Django 5.0.4 on 2024-06-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(db_column='fecha_Entrega')),
                ('estado', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('prioridad', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('responsable', models.TextField()),
            ],
            options={
                'db_table': 'Transaccion_orden',
                'managed': True,
            },
        ),
    ]
