# Generated by Django 5.0.4 on 2024-07-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_salidasmporden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salidasmporden',
            options={'managed': False},
        ),
    ]
