# Generated by Django 5.0.4 on 2024-07-03 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_alter_salidasmporden_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salidasmporden',
            table='Salidas_Mp_Orden',
        ),
    ]
