# Generated by Django 5.0.4 on 2024-06-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ajustes',
            fields=[
                ('id_ajuste', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ajustes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Averias',
            fields=[
                ('id_averia', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Averias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('cod_inventario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('tipo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.TextField()),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransaccionAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ajuste', models.DateField()),
                ('cant_ajuste', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Transaccion_ajuste',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransaccionAverias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_averia', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('fecha_averia', models.DateField()),
            ],
            options={
                'db_table': 'Transaccion_averias',
                'managed': False,
            },
        ),
    ]
