# Generated by Django 5.0.4 on 2024-07-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('nit', models.DecimalField(db_column='Nit', decimal_places=10, max_digits=2, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('direccion', models.TextField()),
                ('telefono', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('email', models.TextField()),
            ],
            options={
                'db_table': 'Clientes',
                'managed': True,
            },
        ),
    ]
