# Generated by Django 5.0.4 on 2024-07-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('nfactura', models.IntegerField(db_column='Nfactura', primary_key=True, serialize=False)),
                ('fecha_facturacion', models.DateField()),
                ('total_factura', models.FloatField()),
            ],
            options={
                'db_table': 'Facturas ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id_orden', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Orden_produccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Remisiones',
            fields=[
                ('nremision', models.IntegerField(db_column='Nremision', primary_key=True, serialize=False)),
                ('fecha_remision', models.DateField()),
                ('total_remision', models.FloatField()),
            ],
            options={
                'db_table': 'Remisiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransaccionFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_inventario', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('fecha_factura', models.DateField()),
            ],
            options={
                'db_table': 'Transaccion_Factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransaccionRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_inventario', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('fecha_remision', models.DateField()),
            ],
            options={
                'db_table': 'Transaccion_Remision',
                'managed': False,
            },
        ),
    ]
