# Generated by Django 5.0.4 on 2024-07-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_facturas_ordenproduccion_remisiones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajustes',
            fields=[
                ('id_ajuste', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ajustes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Averias',
            fields=[
                ('id_averia', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Averias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.IntegerField(primary_key=True, serialize=False)),
                ('total_factura', models.IntegerField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'compras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('cod_inventario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('tipo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProduccionSalidasmporden',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_salida', models.DateField()),
            ],
            options={
                'db_table': 'produccion_salidasmporden',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.TextField()),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SalidasMpOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_e_produccion', models.DateField(blank=True, db_column='fecha_E_produccion', null=True)),
            ],
            options={
                'db_table': 'Salidas_Mp_Orden',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransaccionAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ajuste', models.DateField()),
                ('cant_ajuste', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Transaccion_ajuste',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransaccionAverias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_averia', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('fecha_averia', models.DateField()),
            ],
            options={
                'db_table': 'Transaccion_averias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransaccionOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(db_column='fecha_Entrega')),
                ('estado', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('prioridad', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('responsable', models.TextField()),
                ('fecha_terminacion_orden', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Transaccion_orden',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transformulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('materia1', models.IntegerField(blank=True, null=True)),
                ('cant_materia1', models.FloatField(blank=True, null=True)),
                ('materia2', models.IntegerField(blank=True, null=True)),
                ('cant_materia2', models.FloatField(blank=True, null=True)),
                ('materia3', models.IntegerField(blank=True, null=True)),
                ('cant_materia3', models.FloatField(blank=True, null=True)),
                ('materia4', models.IntegerField(blank=True, null=True)),
                ('cant_materia4', models.FloatField(blank=True, null=True)),
                ('materia5', models.IntegerField(blank=True, null=True)),
                ('cant_materia5', models.FloatField(blank=True, null=True)),
                ('materia6', models.IntegerField(blank=True, null=True)),
                ('cant_materia6', models.FloatField(blank=True, null=True)),
                ('materia7', models.IntegerField(blank=True, null=True)),
                ('cant_materia7', models.FloatField(blank=True, null=True)),
                ('materia8', models.IntegerField(blank=True, null=True)),
                ('cant_materia8', models.FloatField(blank=True, null=True)),
                ('porcentajeiva', models.FloatField()),
                ('pocentajeutilidad', models.FloatField()),
                ('costosindirectos', models.FloatField()),
            ],
            options={
                'db_table': 'transformulas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransMp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mp', models.TextField()),
                ('cant_mp', models.IntegerField()),
                ('costo_unitario', models.FloatField()),
                ('total_linea', models.FloatField()),
                ('fecha_ingreso', models.DateField()),
                ('unidad_medida', models.TextField()),
                ('id_proveedor', models.IntegerField()),
                ('tipo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trans_mp',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('id_factura', models.IntegerField()),
                ('id_remi', models.IntegerField()),
            ],
            options={
                'db_table': 'Ventas',
                'managed': True,
            },
        ),
    ]
